language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: webisteme
  password:
    secure: GiUXWFbuwBf8rvW9V/u2AyTmRtB5QvwZMQ1nK3UYUUgdvn7iTfDANNDSgwtW+abctGTvFhBbD9Q7n7B9g09A/eRXAB7Cw49x/lKQPvSHiWPzifDsmQurC6Mcc4DFJZ+VvU5InN53tSPQ/hjygAtydbn63DS4n3ocyA6Reeqzo0L5Z0ZLYp2V0t/HGl1RzLaB1i+GmlxEBAprnOWDwuAa8wE8VbZ2EwYc/7zPyw7CoibdSnHSQvMGrd5n1VLkY+M6Zraglv8pv9lFJNxPWKs1ItTDzH+pzQIIsiJftJ1Aw3ZjBoYVczFbELoJQbw5IHhDegH6NnLGkn/nWE7o6LLXLmYE3Iow0u2atSU4jOiY0O+SaePiSU2WfvuNN4OP18rBOgLdfdHGPwyvfu1bY/KHONvFZY/5cZ4v7lY9hqr34WMV8TlGpNfiYb3Ke7O1rAsBYRbuhxgGgusi2LY48uBApUFdLDQdTHcDDxn3JCMZLqylR1neMJxn3NQI02MEzJh8nvPV+ULG680v6Zk/6HzZFVIUEi1AVN7XYYmnHQlORutkGkdEIU2sXPeQOCDNqIZ4uy3Ue8cSVuC+bYyWPiSxcgHnu9j5gTYxBio6xaaf0MdzLpesDJbNqvXREFrNzsWelgJQvhT7UcHmaWdUVZ5ClTJ3WiRl4KHV9iXM5FYVcNM=
  on:
    tags: true
    repo: gothill/pyradix-dlt
    python: 3.8
